package com.nsi.domain.core;
// Generated Oct 27, 2017 1:53:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CronEmail generated by hbm2java
 */
@Entity
@Table(name = "cron_email")
public class CronEmail implements java.io.Serializable {

    private long id;
    private String cif;
    private String type;
    private String url;
    private String value;
    private Integer status;
    private Date createdDate;

    public CronEmail() {
    }

    public CronEmail(long id, String cif, String type, String url, String value, Date createdDate) {
        this.id = id;
        this.cif = cif;
        this.type = type;
        this.url = url;
        this.value = value;
        this.createdDate = createdDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "log_generator")
    @SequenceGenerator(name = "log_generator", sequenceName = "cron_email_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "cif", nullable = false, length = 20)
    public String getCif() {
        return this.cif;
    }

    public void setCif(String cif) {
        this.cif = cif;
    }

    @Column(name = "type", nullable = false, length = 20)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "url", nullable = false)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "value", nullable = false)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "status", nullable = false, length = 5)
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 29)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

}
